branch-defaults:
  master:
    environment: caretestexpress
    group_suffix: null
environment-defaults:
  caretestexpress:
    branch: null
    repository: null
global:
  application_name: caretest
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
